kind: pipeline
name: default
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: test-init
  image: busybox
  commands:
  - chmod o+w /drone/src
- name: test
  image: node:12
  user: node
  commands:
  - npm install
  - npm test
- name: docker
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/melinda-rest-api-http
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: secret
name: docker_username
data: O8ILyMm9c1vMACCsVwpR5LMtHzZUlwVm8/kSRcZTnUZzfH4j3VQyj8mtvjADpRFGmcA=
---
kind: secret
name: docker_password
data: /dHEqODPc7fj/utHITiJBKBNB2kpMEi53H1nImIfCmIh/aVSJVnYbIMpe/l6wMhUODsImaKutLOFpD6nka6+yRnyJlFnBsbEi8YdupAoJnHNj+w9zcFqVZXo8tU
