---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:

  - name: generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  - name: audit
    image: node:12
    commands:
      - npm audit --package-lock-only --audit-level=moderate --production

  - name: install
    image: node:12
    commands:
      - npm ci
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: true

  - name: test
    image: node:12
    commands:
      - npm test

  #- name: check-coverage
  #  image: node:12
  #  commands:
  #    - npm run check-coverage

  - name: build
    image: node:12
    commands:
      - npm run build
      - NPM_CONFIG_IGNORE_SCRIPTS=true npm ci --production

  - name: static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: docker 
    image: plugins/docker
    settings:
      repo: quay.io/natlibfi/melinda-rest-api-http
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:

  - name: publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: docker_username
data: AejMpBmWwDw5zVwIuKkFgvvMXKD5Xs36fKRVLTO+jHITKSRpvplM+BUrQvWbR6JdgIU=
---
kind: secret
name: docker_password
data: XJYK8sxY/7vpd0FdISIJipfcgR3NgfJVu2STsttb/Cj8LEtMC6qnCGAzpnprOwds8fl68RnRZ1XuJeEmcLJswpyigGpezeZ7ubQPaW7+vu94cM2oFVq+PwFQ9NE=
---
kind: secret
name: ssh_key
data: /YTdOrUmmHUIa0+MV2JQtGyVvQJPulRpJj9ohAC+f+3eelXat1LN02pwYnB1e0jUGYCjt3eHn+5gO+GtuTw/9CfdS3BT9NplOkLW9INZq4Fn670dIvW2cj9kKoYNL81/qOAl1lkW28p6OxjlSnpWK1Xki/jeFcB0bWPLPxW1fjNrQIZZMIkT+EwJOpP/fDq+ap23puyhwguAz756xJee16e/JubCoGiP8ev4kd1p1M83ToWzvY9ip0IoK9WnW94g0T/2AIT4yFALqmx6DU3KSNya4i47z0JRdp5AL3vsWQJX5+j/aaLsE7id5+sIFvnvpcyxDmqTKPpskyA6Pa+6IvJRxA5zQuwxtV0zFGJqJEYhqds2pFaBjPaCQ2G5n5eBCWEpUmABBfg8auAeJwyqS9CQTezoY2rVNdE9Ha/mVeF8f1hI4adiVtE50RZmD5Vfdt0X6bnp8V64H8yfbjVzGYEjh8KJZVmzcmPak4UkJpWHt3J2/ex9HTf2v2plD2v3n+NeXIB2Ft/reUmGwTukqgJtOnATsCFB9fS/fP9QhEGq7j6ENdS9f9iAOvsa1gwVqdw9O+exC+Uv444dyOydbQe+NNqLVpFjWywlAdMTpACxfwtE7rb60SVutAOGEwpQYas59h59Dq6H0viXS7vC4gKjRytE5MfrjEct7ZLWN0FKQVKRBatwTZ2HMDxGQxoA266SmsUZxLpZQ20XxbGq1JgTb21Ft76ScLPOGupymO/8I7BPxJSp3RNY+Rbj0dlM9+8cpie+iCoB9ptlLuDsTtXuMARgAKa4KVEHVPtKs2Cm5ztss1iq1uzo3nevsL2uZe+pO9x39l9A4ixG3Nuh6qYUY0I3Z+wSWZ57TeDhXJjkSXT6YtHBIZyPI3mIHZBm2966LPk2hsFRMjXZ9GkpIyrAGF4a1D3khcX14Xe4kLFW5HycB5b9QNOV6ZzA8fxeGB133wU7BcIr3k2+yZT24qPHEb5HhEiPZg+88uWE18vD/U2yJnbcQh420taNuC+XKE+FdBd4/RCjoeUfaERrhuHzE7TkhHh2RmuBv6Wszmax0VZxBL9RTV8T6kvZpXQMeETd9n1pSaCrgK3PeuqmIZaoWa6JInNs0Eo1B+xLah+CWWDw3gL15TxeC4g3M8XQV895oDo62dN7GCX4Vso50/oBMSm7e+pajRdtD7ECX/KUfh1TLCEU/judv4OciXhSq4Oc4VsNeoj/tI2O9JA/HzRn0lMD0kAvyG1JAi3UrZmUYeTYY+tIkPKLsRkTt3ClWiDuikhvVRc/VWdpnnHbIXFI/3ohscGs0ii79XAobfFd4lalmpaYQs02NCZqKy+WcJ4kV1bvTHl5dDeXixIvx+VKZ9MRNl7e2kFh7uiVGN5WoTTY5TpXJaH0XKXIBHhMTtO8uBWSjNdpejp96DE3PBkn/mVRuCfNhCm+SfC6X7vdZS8QQ/ZZkzMh5bMhEPfwcYZNXgvSiL31yHMrkMmU9lsxXTFzi/u7u9Kr6+g2KTTgpnVQtYx2lyynI6+g7cqbYX7kWxrp0gbbdcq0isBh6cWchvn68Oxl7bFv1bK1f2kFxjFas2X9tOao97KoeFY0XrZQ0ydy6ByYcDjfMm/d9eytHEhmvnRQ6azYN1zm45KsdtPh5QWkyNJ61bEk7NlUEEF+AkCbO6FuhrLoWzTnUBhQRk+90EMDIaIKtljeECahFfJjXU9G0tTvTaIE12aK7jRKv0to/RCGAFpGoiOgpIlAuNBIn1iDwEPQQ4qj22FpOlDoZuyH857m6nR4UijeRLCoBhzaGzfvtwWWRQ15E0QkITpbBMmInj+Yn1WFuOXGoOD3KSc4sKSQ7dcVwO7uP76kAQFfAThyJKXrxviqznBOAY08lp2T8UK9KxPF7Bondvf0vwPPamsqrFWZ9ibl7PABaoO/AJc8BZ0f48pzulv9uh4U8ykUR+4StjYjwkL1W1GGg3nm5uJZVk89rxZxKmDaXILTm62fa16Rll6JBvQO597P4twQcSc3oCHJEakmXi9zJMWsdF9saa0M31MhQMPmi6FTemLA17CV1hMvZGiwFsFJkQqnmZn1hstHRurrazhAVSciVDoKufvLV6qV+mtfnRh9jBLBwiCX6VI2G/3XpI2LoxYid3onvX9rOdnB40fgi78LTZwPecGNUkfSxuPUse6SGHprcrpiX1uTdM1TV/B0qg1WanBYj0g7XKza76m5tcDwYY9cbE8J/aC0b2CAsNYt9L8ccc6PZzGTr2iCIMNwi7zNeBumvcA+xNVGMihSmp+mIib654gwGY5Ruca/XHHme/v3euYhZ+33lLGT7p7Nqne6HJAt0boEym4aBE9Veu3Ugn6CY+W5fizZFZSoOlKpDIJqLzOahULiGPzTXvuo+BJ5kF1ZjDDdVyNy04++YrPlHCv6Oo24EHnEEnBQ9JhwcO4Yy192/BTI9M7RCPbUCbv4hiMUgBoh+noLvXRTMYw2ezCNLskqeoryoWqe0rNVxy6gTsP84w7ORRsT/6qmD07qG/p2JoCm3V3tJg5wsv7sRwgF4DV4lZl/wzDLd/kAtML2k1RP2+vHXUjY/bjBrTbJRglHtJI1v8m/MWgZDJ7Lz+6StEXD+Ht0NhsIBJCr/ldvuw4aWIKcJZoWZ0c1yP5NvRAz/9A+MYqcsT+SUVHb5Sel2NnezC8WmLw6kEGpmSAFiWPJ7QQTiniJC2ZDXZmd2Su4OFnouKlFpLJ7+2NoxSO5LAKM8S1uo/eHglux/0Nt6Um2oKytbR3FeiK3RkjtWkgsj0QPDsKuqBN3JuzCcOWDLS8T8sPcm1JKtXtCLZuKaojxZUEhnqqqkhIGPm5gkcQt37q4ynhJ7qLs4tBDTO9p0pcWM9pupLg9Jm2UNeAjMc6C85SwPSmkq6p58e/a8y4cv9ljw1Qd0BF1zDl+pZbnPV6VUnOXDJw2fncgRXOk60Qx4tRBUOE6K7q43G7d6QBvaSCf9xsknPGrl6IHBifCLgIspN9aCTJrijLbK7SsetMn
---
kind: secret
name: gpg_key
data: zhLXTrpq/wvQ1YbaIvNoeeZy81FizMXlEAMzb7ZSwLQKB6lpalcf5GQBWP5nu9k2fXOYzCAWxG45j/nyGcx3AAEamlltAEwgnI+l1MoBmH2/DA1vABespLTx1zRhbIpFrvuWlXaAq8sVtlX/x6EqgBKZAleptOWFk8WnxcCjnomLJHfIRCzwSkr7te153e4/1mw4r514EAJlkEAV0sfROnRA1usPJQsQSazrv9ch4PpxnnBpFnKuduZHrMtEZVQQPREIJQDl5iib92VSdBqhR7VUiF0ZVZImEiT35Whu7wtY4/V2dn4RPkQSFqhuFuceWqBihBLYPJVsw6rtb/IstN8D8SbdyNiixKS49LwTo5qqiAjtYWgDslk6z5xF34LHI/d72Iag1cpaXpxvG0eG+nVu7jdxoSIFoD8CLDA6mVYkGByQCvNuyPwfHe4r6zebYy/pqK2bCv95CzsS7ltIy3ISkUpCKJDXL48qImAl6mX08GwRf/yG1g/94t5bgttY7bOYJIa/U8cy78e0t38UlNPw9ZJ9tdYJ0JchxNmG8e7asQTlYyH+x6+aoXnV3Lo4UhfWa53FYCmqX2qBbvz/te1SIisfziNg0hA4YOfk7SEWQJTuZ+btJAN6lm/fcPsHquInWy00r8R8I1bRAlIDw2BIx5uny3hdWpV6MZOV/jz0smwNFl5nm+DVvbKhM+kfi8T5NK3Xf5p5/hCcUqC7r44gfrQ9ceyCGsTqHA0P2S8AZ5kiq7HqrT4K36lcPNwwhotFJE94uUnx5bfeW+ovqVy5piWq6+bs1RST9wISKc9dzVKggzc8jqy6Xors1N8ofAnp5ECp+Ny0k2oFaYVsyMGmG+B4iAEfLRwAPjHTvu8+b1CJErflMrLM+cUr0xceF5e7n2ndnTWWrZV36vrckG+9KgiK7zCQo9s6KCItZf8kCMLI8T1S2o4QXxRiwjCiSaWRdV7yH0VLONT5yL5L6r4B/tY2uMVmKIUPHST++76gb5ED2NF6BK86OrbPaqHauiaDa5EMMgX4w0w1eHTo+f5QciC4ZupOXp0/zUJiTCyvc+9qQC1yqFeE9s97ltUKgPNPHdh6rTO2phJ3wRci6cNSBiFR4sOGUTPPWTVdJnDLmAUNPYkuTLbpja2c3ZmE5scnM0iX98nd6V4bA8MlxbD9ODK4763b4uIGGFvpg6DOnqh70i9HLZ6XNh9rvHCCS0+F3G8VNELCrxhjoXu/ikk+Grec8NG+d2VRyRNeAx2sN+QoSyWk5BwYtF036xBKrgK8jHH9VesKRtLN37NNrjs0j1lI2dYPV30odlOWpDJKW6qnhNHVyr6kFW9HQUZF9ZaxT8/BFrDHMw5BuDHtXWHWMIMUZfFR8RJ/SW6t4qJIMW05vjl49RRA9BNvE4mu7UC090stJfYhujBqG5PclcnNKWGEoeacwYrwY2wlZq1F9Ah21fdhGnoIiuInWwO68CyJHvIyvc+4bII40DEGaIp4fCzw0e0FMcEst8qG88/QpeST/L4SlO3Kavz/7mXDZfPfJRKI50LvhwZ/dT0NDilqK0mOUPEd9I1g3niHxHvw3Otvxpcc/EBfUgbEC91Td2GDSmvvc80xFeSGE22OlEWjZzsGlzQWpuOlRYSqzUsIasEqAu7XAmkHQTmb4N1HGMzJt65ePS6zYxeBXIqUH7vZgydyeBu5x59Fm1AUU23Jt8OZUe6qUaUXdBj03iDdGoza5JCTfz5d54EIDJWCDQQaVVxZGnON59rmrfu1LQ0+TPgPdNCHprveDSV47dIZ5dJ/HTB8FKRhg+QWYvN6rGQmNQ+IswXTiKJxo+b/Qxr7cqxm5eJJV95QeWGPe5yUiNWz3m+lzsuDJofjEWmQvDEYyztc1M9X9P9xLnNNVT0m9RpLxyqqhqBtNdFhRhmDqrN01YO0Nc0HVjKxaVxedZbLlqmffzl7o65jgmRuTUU2RdYl8GYqbGFuRgBZSDGlVU0vTb+HUYMDidZFtfube9f57wfXpMF/gj4b+wrVj3+EP1ulcmTzmRFhsyI4uZyM4HIeDjRbhRYgZC+WI+QqBWSxtWvp8/Xws+VhkEwUN/BsnnIW64DISUxBVrnUh671d3MYa/PLjMDbElaEh9W40Y5waHatKyztI7ZXArB7ZUMconr/8GxkHfwUny6vOXvFEQrpWtUR796cBo3+P5p19HXULd6AOpbVp2sqZ8ve9hGZPRyHi5h3q1rjjIOjiWd0K1fFXSt9wAiR7cnXT1GXwDHfEDoWbrFtB9isHJJpDzMlaIb6qS6SnudqQfSeu3cJu9WN/h/FFjYKrkkiA6jfIJ5Z1E/1CG4ukjHG+QfkyTwiVnrfii/qq+bs46jPXLDQYHZWExoapec/oofT4eWCp/GfnkWtigEI2qxw7snFFNAOrA4ZNroY8EsocPp7d7hTK9FccJliaOtUkgiE5cIck0gJULlBEGhZK1I8SPihpxdaz4Pw9/z/XBqmJ3QbkaHEf+MTo2+joL9jgO76R0elRqrZbZX31+HrTEX8yIo9cj7SL0d8Km8Zn+U6vEl+hb/YsTGk9pE1FbTuy0IevLagNdy4ksRyn+9+o0TwTHHomHqC0ilFw05GtSKkn6GQQauV/O36fuROTE+GiM14sUS7obeXK+tb2oDIWB444azx8FSANKpb3ct6bER9pW5kl2E5WqT95a3S9LvMMXSxbHQGwRAm5cNgYKXRSv+6hi36ubCrY8zT+eD8wvMxMwgmPPV08pm5pSXKd99dYer5RtArwhZx1XfGBhtsAqaHZr83NjYflZUDevYAzPhHDNZ8TeBsSz8QP5pCNWwn7yqdDNPUarjM63lrlXIOapPzpw+4UzjwnQAbAl2yCJO0gh8g8sRiTOR/cI5UzfukyLj4azja3NyYJqx89yFNNSEYxS/ixwwfQbqADrBz2HVPFTYCRWWDuQyBlYzUYMY0ibFhz94fE5PDR5XLFG1I46UiMll1IAIG1z2mnUNynHunR/YmD2t0WokyXTTLF9HdTYbF9ceHKqHR2TUI0gVoigXCqvde9J0dWnqnIWdnwXPGjRKmbeyjht0k82FxzLPxljoV3ThPPu+lpFu90ffALqqB3LyqykiUiLgSdNAm5EHIsTjmUIsQwJ2KDXTcxxCW6SHWLHAwKcRdgD8Pvu/7ZjrjfPqM+p8HS+NSxiDBYpWMNbAQxO6lDNvgpRIT9Uu5Agr9RwK4fZSmoWKNUAcSfRNJ9TakVJC6WQLxRwulAuyyIAQE0+3CJ4e/Ml10L22vIm1AYe2cC2SIzRGdF+5yshCgTTA/lQ5mKWxb1h3mfZ1YjeByz4x6jXB6/+D3dBTz898AUhkXkjBWVcJy80x2D8r256o6ISm+uuNTaANUb0D+0a6ubFTc71IVvys/I26l9nIZ3vdBc0bqL0UMVtE4tT8ngbnR0vIg6jJm3jkqPyjJceYFcGXzY+O2cuRoUrqRMfrOMbzAwvb91lIKt/zWTsdQ1Kr80RR32pZPQLx0EY9tukqhzjaaZFDJ0eWrVCVEyN9BJWJOPqjccGOwdRi6Y5smGYRuuGVoY8/thV+b8itK2BXClrlQlO0l44YNvUPlrKcC8UTgeFglV7uwL8SnRnqnmtvBnm4dlg+b/guSR95kr+6ZPpEPfCKfv7IJWj5zf9EdFMXHMwJQjf0NXe1UDyHMMVJhxQJ/u4a/AxkIYXsWWYGNelQygqkYBSHEFBfmQmyaUGv16Mfl9UafY1TZIWmyQXwa4Gqdsbi7u9K7nRgwn0qJLASzy7JFs8vG7G6dgjJVbXSr5DTKTtkfXifYemaTtX6ORRd0cltk/bsgnSliIOGB+WI85kNaS1FHima7MRJUJY3AHbAkQWYtshN5QbedMSIQ+oRymDJMbwqDge3BXoxdO3xlBqBmlLBLgW0a7T7nfOkP7wj5E79SF6b7tmXNJRWtO51Gf5qisloPREAxpLm9REJUGuY5iSZJ1vKjs3ZrmS8OvIt8d7RUX6s78QZCN+k4aXP5uboILWjqsY3FlzTktk01utW9IZdFWdkQGIHRezWfp9XSdwhyCOeAo+5Cjo0TMC87y0y2Mw0Um2UrPpn6Wle8jxPq+KtpVwGKQBNK+M/lOLCed3/WG3Jf832BKu6ahPvF18pam/wKzzccmFzoUgGO3AVatGPMTebnVwCieQ6kjLH8l+gLkbV1pCIYjjgK9SDjkNu+ahaAvaqNtX4LfyhBHpEAZcMdo9iP2vUanafH2YtcQLLatYY8FAR1mkP1njWHKafWc5XZr4xWHXw3B/ipJhY21AXYbVLYmhDYcX+UHbngtfSqLd057E2oJtBDaxH1lVSOxW2k9jDgCkYb7Vex0NP9tCFS9di9fnpW9WkRE5DJ4fnySFo2vfMCVyj1lHW/NZEsxygEXoVMF1I1l7bL/elAVlFlynFNhJ7VpIDRRsC7I1M+rAicEDwn18vs6s6v39NQt0dPSYH57mRwi3dbHrJctMzB3f2CjJPsQqMB+fwsHHm2zybCqJH4Yo5jiRSCKAzZzW/lT00pqXnvgYkh4UEMRlCNCFxtkpIIAd6FAh2qt4cnW1FitaLwYWGvd57bCxWWO8daDl5CaF3RCv8SVdrZma602TC2nFN2QMnHYOs1zOFJ4aSCk2g9XdPbZs2kuEGH01cI9VlZ+w4eD/8fcn9yJAmlz8anzYcgzp1WKj3isXTZIIYPlgFhFfloLxNopnlDSYGW7RHmlF0lnqCohimJAnL9S1xi3TEVfZVisUwdVDIcH54JOBo+oTxp/ZXNfdQ8A5no1Ao4aoKtwCzdow79LYYSjsaIagOhPWWrXyjddq1ilJG2Kztqlf8ZZJcEivbF+8P9HtDA6truGCKlYBaqMsp7Cao36dK1lEtBaya/FUkDmfSCyL9K6fzAcWuTInHGCDC/46HGQyCYZwggEjNOv6iKmOdQ1MgTBjUPZF/8nMsWDcsnVCaPjxie66YqpFUBxXVWydl8bx75AwN32aH4JdW1bq6tGNc6/oFKom8CUMOSzCinZq0XDirVQ4LsRlpt6imnz2ID/LafGbGNqFGhZwtmpx7v4fTnz4Nbsextv8GeMvuvNyS5kNCO3xy0oUyjkZA3RYGsZ2nazlGq8IURoJYMicT4iXBmRkBypuAv8FJYy1SfQo8WhEd/YEQmPObR4riO0KSRMxkfTJjL4DsvL2SoEv3T6tNd+nfzsleGqgk83Tas9lifEH/zXAJheO7iP2JtosmQIaltzLoRgHbzJFlDjopP56uaCj2s8sBxnaoTHF1YmikcBl0Qf/3XBRV0UTNAQtg19PLtsVvICWDwVXu+nyDn0k3OjGSW+bY/YgO1ZLlRC3zGfoyNNi9l6JV2EJTlfdRXjqVox9Rwoapp6IkfkQNNJ7Jy7dYqxPIjmSge1EyY6YZXm4KbZgPCEuWNUH4ydqHrdBkB9I8w5R6FGFJ3C7i1yiUlnnENxg68GAeoqVTGD5Szl6/R0XOmRzI6bxBPtLifx4KKfno131CKLKy1Kiv0Oes3G7ASy1H0IWKxfIqdiKQE2lZuln6ZG9Pz1kf8Vs6GnL5mWWXi+byfLIlvjhjoePo+LQMR/g94L1O8ZwoRqqk2UunPUrbmTaukCjR5DlNbvS7NkpNxBZlcQ7e3lDufqgt0NJkX/kIEg4wtY2orlWJT/a/OONEZcVmpyeUlg+mMWfJIcRRsG0ScyxYgXqP+wS7zRwokK0pywyqpCSKiT09HxK6L3znS93u7TnaqTBiz+4e1qPbKa2KZOfrgL5Bvh0mcT/oLoKtBB4GNZhhpJZX1QL044nS+NX2O1WYl0Q88bZ9huiburW+Lf/Fr8a+qovS75Ot8KhZgPe0ozrbVPcL6oHAcQpNyJz0iW2Fx1yFgEjedU/zb/CTb6hb1tlblTQusWXowmSi5EibO6/YQnQ25eg0misuL6hCOpaMOEaYGmAjPm0g46RnqvMRAV4BiBTcVKrGOjvrJl4UbrHEIgHO4b/T0bkvdYSeBdbT68FHLZMu8KZL4HvBZRt5v9TCd/zpmwKHHpD18AQMYSpHNeHDkNXKP7ziaxau+h82DkMmHC7crk7N5wUBBp8vomYPCInMQ9b6Nmdy6W+D9C7k3c0tmfvCmLkAH3GEmZndaGWE4gL15qb3polJIgbaue3RcFpoeBY59FWO8xjX+6hTpiDI48DYBzv3yV4RzzbrEchKMGd3AnpN5AsIuapiEg9ijr+JXH8ecuMqm45FVghCTlu0mppmUbrKMCeCzYcGia21i1/W0paU6jXscqtsJrFerJ+qLwK+VXD6hs7Am8f9/F5qWLFwt6ch8pGonAOl7nSlJ0HG/TnjR07ZL2YAKu3UPA5T7y41bxTLgIgmJUQMb6NsAzYrHbW6edIqy0GJw5zi75LR8ZcIvjIERqubR3sxLUKT3rNRQaUaW3cbnaJKVPq9rikqJi9nY1yGQEh+hhLYiErN+TVC4RjDrrXhOlqi8Cqwdb4hisPqvA+CO5enDOC4Q4NXdAfsh4FypqaLgXFJgsR/MeyL4OpRUwWt6OoZv1ailZ6BwOTjynr8EGtP7X4I70zlqguWAS/3H9YBg4V07O9k3UGVdZ87GSuF4VDY6odZj9qAia3K9BMNnBdZ0NjbzNw5EDfAGKy0B7ZlSxQ36W1JY6UCr6znx7AJQyJ9eFOgv4ZYuPJovXmQVEgO/8TKt0ADJBTnkR9GXqWArEw==
---
kind: signature
hmac: 2de2c405383c3328c6aeb3c483c48b6ff13e86cea570c41a11be596dec18b8a2

...
