kind: pipeline
name: default
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: test-init
  image: busybox
  commands:
  - chmod o+w /drone/src
- name: test
  image: node:12
  user: node
  commands:
  - npm install
  - npm test
- name: docker
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/melinda-rest-api-http
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: secret
name: docker_username
data: AejMpBmWwDw5zVwIuKkFgvvMXKD5Xs36fKRVLTO+jHITKSRpvplM+BUrQvWbR6JdgIU=
---
kind: secret
name: docker_password
data: XJYK8sxY/7vpd0FdISIJipfcgR3NgfJVu2STsttb/Cj8LEtMC6qnCGAzpnprOwds8fl68RnRZ1XuJeEmcLJswpyigGpezeZ7ubQPaW7+vu94cM2oFVq+PwFQ9NE=